version: "3"

services:
  vote:
    image: bharathkumarraju/examplevotingapp_vote_bkr
    command: python app.py
    ports:
      - "5000:80"
  result:
    image: bharathkumarraju/examplevotingapp_result_bkr
    command: nodemon server.js
    ports:
      - "5001:80"
      - "5858:5858"
  worker:
    image: bharathkumarraju/examplevotingapp_worker_bkr
  redis:
    image: redis:alpine
    ports: ["6379"]

  db:
    image: postgres:9.4
